.NH
This Is A Heading
.LP
this is a paragraph

.\" start source code block
.SOURCE
#! /usr/bin/env perl

my $version = 'This is a source code block';
print $line;
.SOURCE stop
.\" end source code block

.LP
just make sure this prints

.\" this is another code block in c
.SOURCE
#! /usr/bin/env perl

my $version = 'This is a source code block';
print $line;
.SOURCE stop
.\" end source code block

.LP
just make sure this prints

